// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyqiiwitxmexkuyeojsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cWlpd2l0eG1leGt1eWVvanNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzEzODQsImV4cCI6MjA3MzU0NzM4NH0.ZzBtMnMvQkxa7N8GVS1ZJRfNhEDlJNB9W0TYE50dOcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});